Aws:
  AwsS3:
    buckets:
      knowledgebase: "rag-knowledgebase-staging"
      crawler: "rag-crawler-staging"
  AwsSqs:
    Queues:
      FileProcessingQueue: "File-Processing-Queue-Staging"
      CrawlContentQueue: "Crawl-Content-Queue-Staging"
Azure:
  S3:
    buckets:
      knowledgebase: "rag-knowledgebase-staging"
      crawler: "rag-crawler-staging"
  ServiceBus:
    Queues:
      FileProcessingQueue: "File-Processing-Queue-Staging"
      CrawlContentQueue: "Crawl-Content-Queue-Staging"